/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignaturesRouteImport } from './routes/signatures'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnrollmentRouteImport } from './routes/enrollment'
import { Route as EnrollDocumentsRouteImport } from './routes/enroll-documents'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignaturesIndexRouteImport } from './routes/signatures/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as SignaturesIdRouteImport } from './routes/signatures/$id'
import { Route as FiuIdRouteImport } from './routes/fiu.$id'
import { Route as DocumentsIdRouteImport } from './routes/documents/$id'
import { Route as ChatIdRouteImport } from './routes/chat/$id'
import { Route as CapIdRouteImport } from './routes/cap.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignaturesRoute = SignaturesRouteImport.update({
  id: '/signatures',
  path: '/signatures',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentRoute = EnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollDocumentsRoute = EnrollDocumentsRouteImport.update({
  id: '/enroll-documents',
  path: '/enroll-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignaturesIndexRoute = SignaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignaturesRoute,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SignaturesIdRoute = SignaturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SignaturesRoute,
} as any)
const FiuIdRoute = FiuIdRouteImport.update({
  id: '/fiu/$id',
  path: '/fiu/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentsRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatRoute,
} as any)
const CapIdRoute = CapIdRouteImport.update({
  id: '/cap/$id',
  path: '/cap/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/enroll-documents': typeof EnrollDocumentsRoute
  '/enrollment': typeof EnrollmentRoute
  '/login': typeof LoginRoute
  '/signatures': typeof SignaturesRouteWithChildren
  '/signup': typeof SignupRoute
  '/cap/$id': typeof CapIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/fiu/$id': typeof FiuIdRoute
  '/signatures/$id': typeof SignaturesIdRoute
  '/chat/': typeof ChatIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/signatures/': typeof SignaturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enroll-documents': typeof EnrollDocumentsRoute
  '/enrollment': typeof EnrollmentRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/cap/$id': typeof CapIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/fiu/$id': typeof FiuIdRoute
  '/signatures/$id': typeof SignaturesIdRoute
  '/chat': typeof ChatIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/signatures': typeof SignaturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/enroll-documents': typeof EnrollDocumentsRoute
  '/enrollment': typeof EnrollmentRoute
  '/login': typeof LoginRoute
  '/signatures': typeof SignaturesRouteWithChildren
  '/signup': typeof SignupRoute
  '/cap/$id': typeof CapIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/fiu/$id': typeof FiuIdRoute
  '/signatures/$id': typeof SignaturesIdRoute
  '/chat/': typeof ChatIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/signatures/': typeof SignaturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/documents'
    | '/enroll-documents'
    | '/enrollment'
    | '/login'
    | '/signatures'
    | '/signup'
    | '/cap/$id'
    | '/chat/$id'
    | '/documents/$id'
    | '/fiu/$id'
    | '/signatures/$id'
    | '/chat/'
    | '/documents/'
    | '/signatures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enroll-documents'
    | '/enrollment'
    | '/login'
    | '/signup'
    | '/cap/$id'
    | '/chat/$id'
    | '/documents/$id'
    | '/fiu/$id'
    | '/signatures/$id'
    | '/chat'
    | '/documents'
    | '/signatures'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/documents'
    | '/enroll-documents'
    | '/enrollment'
    | '/login'
    | '/signatures'
    | '/signup'
    | '/cap/$id'
    | '/chat/$id'
    | '/documents/$id'
    | '/fiu/$id'
    | '/signatures/$id'
    | '/chat/'
    | '/documents/'
    | '/signatures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  DocumentsRoute: typeof DocumentsRouteWithChildren
  EnrollDocumentsRoute: typeof EnrollDocumentsRoute
  EnrollmentRoute: typeof EnrollmentRoute
  LoginRoute: typeof LoginRoute
  SignaturesRoute: typeof SignaturesRouteWithChildren
  SignupRoute: typeof SignupRoute
  CapIdRoute: typeof CapIdRoute
  FiuIdRoute: typeof FiuIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signatures': {
      id: '/signatures'
      path: '/signatures'
      fullPath: '/signatures'
      preLoaderRoute: typeof SignaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment': {
      id: '/enrollment'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof EnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll-documents': {
      id: '/enroll-documents'
      path: '/enroll-documents'
      fullPath: '/enroll-documents'
      preLoaderRoute: typeof EnrollDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signatures/': {
      id: '/signatures/'
      path: '/'
      fullPath: '/signatures/'
      preLoaderRoute: typeof SignaturesIndexRouteImport
      parentRoute: typeof SignaturesRoute
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/signatures/$id': {
      id: '/signatures/$id'
      path: '/$id'
      fullPath: '/signatures/$id'
      preLoaderRoute: typeof SignaturesIdRouteImport
      parentRoute: typeof SignaturesRoute
    }
    '/fiu/$id': {
      id: '/fiu/$id'
      path: '/fiu/$id'
      fullPath: '/fiu/$id'
      preLoaderRoute: typeof FiuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/cap/$id': {
      id: '/cap/$id'
      path: '/cap/$id'
      fullPath: '/cap/$id'
      preLoaderRoute: typeof CapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatIdRoute: typeof ChatIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIdRoute: ChatIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface DocumentsRouteChildren {
  DocumentsIdRoute: typeof DocumentsIdRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsIdRoute: DocumentsIdRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

interface SignaturesRouteChildren {
  SignaturesIdRoute: typeof SignaturesIdRoute
  SignaturesIndexRoute: typeof SignaturesIndexRoute
}

const SignaturesRouteChildren: SignaturesRouteChildren = {
  SignaturesIdRoute: SignaturesIdRoute,
  SignaturesIndexRoute: SignaturesIndexRoute,
}

const SignaturesRouteWithChildren = SignaturesRoute._addFileChildren(
  SignaturesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  DocumentsRoute: DocumentsRouteWithChildren,
  EnrollDocumentsRoute: EnrollDocumentsRoute,
  EnrollmentRoute: EnrollmentRoute,
  LoginRoute: LoginRoute,
  SignaturesRoute: SignaturesRouteWithChildren,
  SignupRoute: SignupRoute,
  CapIdRoute: CapIdRoute,
  FiuIdRoute: FiuIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
